name: Generate STEMaths Lesson with TTS

on:
  workflow_dispatch: # run manually
  schedule:
    - cron: "0 9 * * 1" # every Monday at 9 AM UTC

jobs:
  generate-lesson-and-tts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install @google/generative-ai gtts

      - name: Create content/lessons directory if not exists
        run: mkdir -p content/lessons

      - name: Generate lesson with Gemini
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          node <<'EOF'
          import fs from 'fs';
          import path from 'path';
          import { GoogleGenerativeAI } from '@google/generative-ai';

          const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
          const model = genAI.getGenerativeModel({ model: "gemini-pro" });

          async function generateLesson() {
            const prompt = "Create a simple STEMaths lesson in markdown format on fractions for junior high school.";
            const result = await model.generateContent(prompt);
            const lessonText = result.response.text();

            const lessonPath = path.join('content', 'lessons', 'lesson.md');
            fs.writeFileSync(lessonPath, lessonText);
            console.log(`✅ Lesson saved to ${lessonPath}`);
          }

          generateLesson();
          EOF

      - name: Generate TTS from lesson
        run: |
          node <<'EOF'
          import fs from 'fs';
          import path from 'path';
          import gTTS from 'gtts';

          const lessonPath = path.join('content', 'lessons', 'lesson.md');
          if (!fs.existsSync(lessonPath)) {
            console.error("❌ Lesson file not found, cannot generate TTS.");
            process.exit(1);
          }

          const text = fs.readFileSync(lessonPath, 'utf8');
          const tts = new gTTS(text, 'en');

          const audioPath = path.join('content', 'lessons', 'lesson.mp3');
          tts.save(audioPath, function (err) {
            if (err) { throw err; }
            console.log(`✅ Audio saved to ${audioPath}`);
          });
          EOF

      - name: Commit lesson and audio
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add content/lessons/lesson.md content/lessons/lesson.mp3
          git commit -m "Add new STEMaths lesson and audio" || echo "No changes to commit"
          git push
