name: Generate Localized STEMaths Lesson

on:
  workflow_dispatch:
    inputs:
      lang:
        description: 'Language code (e.g., ewe, twi, ga, hausa)'
        required: true
        default: 'ewe'
      grade:
        description: 'Grade level (e.g., 3)'
        required: true
        default: '3'
      topic:
        description: 'Math topic (e.g., Addition, Fractions)'
        required: true
        default: 'Addition'

jobs:
  generate-lesson:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gemini CLI to generate lesson
        uses: google-github-actions/run-gemini-cli@v0.1.10
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            You are an instructional designer for STEMaths.
            Create ONE math lesson for Grade {{ inputs.grade }} students on the topic "{{ inputs.topic }}" in {{ inputs.lang }}.
            Follow the exact format described in the GEMINI.md file in this repository.
            Save the lesson as:
            content/lessons/{{ inputs.lang }}/grade-{{ inputs.grade }}/lesson-01.md
            Do not overwrite any existing lessons unless instructed.
            Make sure all explanations and vocabulary are in {{ inputs.lang }}, but math notation remains in English/numbers.

          settings: |
            {
              "commit": {
                "enabled": false
              },
              "tools": {
                "fs": true
              }
            }

      - name: Generate TTS audio file from lesson
        run: |
          mkdir -p content/lessons/${{ github.event.inputs.lang }}/grade-${{ github.event.inputs.grade }}
          # Install required TTS package
          pip install gtts
          python - <<'PYCODE'
          from gtts import gTTS
          import pathlib
          lang = "${{ github.event.inputs.lang }}"
          grade = "${{ github.event.inputs.grade }}"
          lesson_file = pathlib.Path(f"content/lessons/{lang}/grade-{grade}/lesson-01.md")
          audio_file = pathlib.Path(f"content/lessons/{lang}/grade-{grade}/lesson-01.mp3")
          text = lesson_file.read_text(encoding="utf-8")
          tts = gTTS(text=text, lang="en")  # Replace 'en' with actual TTS language code if available
          tts.save(audio_file)
          PYCODE

      - name: Commit lesson text and audio
        run: |
          git config user.name "stemaths-bot"
          git config user.email "bot@stemaths.org"
          git add content/lessons/${{ github.event.inputs.lang }}/grade-${{ github.event.inputs.grade }}/lesson-01.md
          git add content/lessons/${{ github.event.inputs.lang }}/grade-${{ github.event.inputs.grade }}/lesson-01.mp3
          git commit -m "chore: add ${{ github.event.inputs.lang }} Grade ${{ github.event.inputs.grade }} lesson on ${{ github.event.inputs.topic }} with audio"
          git push
