name: Generate STEMaths Lesson and TTS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *" # 9 AM UTC daily

jobs:
  generate-lesson-and-tts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install openai

      - name: Ensure lessons directory exists
        run: mkdir -p content/lessons

      - name: Generate STEMaths Lesson and TTS
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python << 'EOF'
          import openai, os, datetime

          openai.api_key = os.getenv("OPENAI_API_KEY")

          # Timestamp for filenames
          timestamp = datetime.datetime.utcnow().strftime("%Y-%m-%d-%H-%M")
          text_path = f"content/lessons/lesson-{timestamp}.md"
          audio_path = f"content/lessons/lesson-{timestamp}.mp3"

          # Generate lesson text
          prompt = """
          Create a STEMaths lesson for secondary school students.
          The lesson should be clear, engaging, and include examples.
          """
          response = openai.ChatCompletion.create(
              model="gpt-4o-mini",
              messages=[{"role": "user", "content": prompt}]
          )
          lesson_text = response.choices[0].message["content"]

          # Save lesson text
          with open(text_path, "w", encoding="utf-8") as f:
              f.write(lesson_text)

          # Generate TTS audio
          audio_resp = openai.Audio.speech.create(
              model="gpt-4o-mini-tts",
              voice="alloy",
              input=lesson_text
          )

          with open(audio_path, "wb") as f:
              f.write(audio_resp.audio)

          print(f"Lesson saved to {text_path}")
          print(f"TTS saved to {audio_path}")
          EOF

      - name: Commit and push lesson + TTS
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add content/lessons/*.md content/lessons/*.mp3
          git commit -m "Add new STEMaths lesson and TTS"
          git push
