name: Generate Localized STEMaths Lesson

on:
  workflow_dispatch:
    inputs:
      lang:
        description: 'Language code (e.g. ewe, twi, ga, hausa)'
        required: true
        default: 'ewe'
      grade:
        description: 'Grade number (e.g. 3, 4, 5)'
        required: true
        default: '3'
      topic:
        description: 'Math topic (e.g. Fractions, Multiplication)'
        required: true
        default: 'Fractions'

jobs:
  generate-lesson:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gemini CLI to generate lesson
        uses: google-github-actions/run-gemini-cli@v0.1.10
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          prompt: |
            You are an instructional designer for STEMaths.
            Create ONE math lesson for Grade {{ inputs.grade }} students
            in the {{ inputs.lang }} language on the topic "{{ inputs.topic }}".
            Follow the exact markdown lesson structure described in GEMINI.md.
            Save the file to:
            content/lessons/{{ inputs.lang }}/grade-{{ inputs.grade }}/lesson-01.md
          settings: |
            {
              "commit": {
                "enabled": true,
                "name": "stemaths-bot",
                "email": "bot@stemaths.org",
                "message": "chore: add {{ inputs.lang }} Grade {{ inputs.grade }} lesson on {{ inputs.topic }}"
              },
              "tools": { "fs": true, "git": true }
            }
