name: Generate Lesson

on:
  workflow_dispatch:
    inputs:
      topic:
        description: "Lesson topic"
        required: true
        default: "Introduction to Fractions"
      grade:
        description: "Target grade level"
        required: true
        default: "Grade 3"
      language:
        description: "Language for the lesson"
        required: true
        default: "English"

jobs:
  generate-lesson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up content folder
        run: mkdir -p content/lessons

      - name: Generate lesson with OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          FILENAME="content/lessons/lesson-$(date +%Y-%m-%d-%H-%M-%S).md"
          PROMPT="Create a detailed, engaging, and age-appropriate lesson plan on the topic: '${{ github.event.inputs.topic }}' for ${{ github.event.inputs.grade }} students in ${{ github.event.inputs.language }}. Include objectives, materials, activities, and an assessment section."

          RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
            -s \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "{
              \"model\": \"gpt-4o-mini\",
              \"messages\": [
                {\"role\": \"system\", \"content\": \"You are an expert lesson plan generator.\"},
                {\"role\": \"user\", \"content\": \"$PROMPT\"}
              ],
              \"max_tokens\": 1200
            }" | jq -r '.choices[0].message.content')

          echo "$RESPONSE" > "$FILENAME"

      - name: Commit and push lesson
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add content/lessons/*.md
          git commit -m "Add new generated lesson: ${{ github.event.inputs.topic }}"
          git push
