name: Generate TTS for Lessons

on:
  push:
    paths:
      - "lessons/*.txt"

jobs:
  tts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install openai

      - name: Generate TTS from lesson
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          import os
          import openai
          import glob

          openai.api_key = os.environ["OPENAI_API_KEY"]

          for file_path in glob.glob("lessons/*.txt"):
              with open(file_path, "r") as f:
                  text_content = f.read()

              mp3_file = file_path.replace(".txt", ".mp3")

              with open(mp3_file, "wb") as audio_file:
                  response = openai.audio.speech.create(
                      model="gpt-4o-mini-tts",
                      voice="alloy",
                      input=text_content
                  )
                  audio_file.write(response.data)

              print(f"Generated: {mp3_file}")

      - name: Commit and push MP3 files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add lessons/*.mp3
          git commit -m "Add generated TTS audio"
          git push
