name: Generate TTS Audio from STEMaths Lesson

on:
  workflow_dispatch:
    inputs:
      lesson_path:
        description: 'Path to the lesson markdown file (e.g., content/lessons/ewe/grade-3/lesson-01.md)'
        required: true
        default: 'content/lessons/ewe/grade-3/lesson-01.md'
      lang:
        description: 'Language code (e.g., ewe, twi, ga, hausa)'
        required: true
        default: 'ewe'

jobs:
  generate-tts:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip install google-genai

      - name: Run TTS generation script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python3 <<'EOF'
          import os
          from pathlib import Path
          from google import genai

          lesson_path = Path("${{ github.event.inputs.lesson_path }}")
          lang = "${{ github.event.inputs.lang }}"

          # Where audio will be stored
          audio_dir = Path(f"assets/audio/{lang}")
          audio_dir.mkdir(parents=True, exist_ok=True)

          # Read lesson text
          with open(lesson_path, "r", encoding="utf-8") as f:
              lesson_text = f.read()

          # Init Gemini client
          client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

          # Generate speech
          print(f"Generating TTS for {lesson_path}...")
          response = client.models.generate_speech(
              model="gemini-2.5-flash-tts",  # or latest TTS model
              input=f"Read aloud the following lesson in {lang}:\n\n{lesson_text}"
          )

          audio_file = audio_dir / (lesson_path.stem + ".mp3")
          with open(audio_file, "wb") as f:
              f.write(response.audio)

          print(f"TTS saved to {audio_file}")
          EOF

      - name: Commit audio file
        run: |
          git config --global user.name "stemaths-bot"
          git config --global user.email "bot@stemaths.org"
          git add assets/audio
          git commit -m "chore: add TTS audio for ${{ github.event.inputs.lesson_path }}"
          git push
