name: Generate Lesson with Audio

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # every day at 9am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Gemini CLI
        run: npm install -g @google/generative-ai-cli

      - name: Authenticate Gemini CLI
        run: |
          echo "${{ secrets.GEMINI_API_KEY }}" > .gemini_api_key
          export GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"

      - name: Create content folder
        run: mkdir -p content/lessons

      - name: Generate lesson and save to file
        run: |
          gemini prompt "Create a STEMaths lesson on fractions in Ewe language." > content/lessons/lesson.md

      - name: Generate TTS audio from lesson
        run: |
          npm install -g @google-cloud/text-to-speech-cli
          gcloud auth activate-service-account --key-file=<(echo "${{ secrets.GOOGLE_CLOUD_KEY }}")
          text-to-speech-cli \
            --input-file content/lessons/lesson.md \
            --voice "en-US-Wavenet-D" \
            --output-file content/lessons/lesson.mp3

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add content/lessons/lesson.md content/lessons/lesson.mp3
          git commit -m "Add new lesson with audio"
          git push
